[package]
name = "yarn-autocompletions"
version = "1.2.0"
authors = ["Pig Fang <g-plane@hotmail.com>"]
edition = "2018"

[dependencies]
dirs = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
